# Generated by Django 5.2.4 on 2025-09-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_tax"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tax",
            options={"verbose_name_plural": "tax"},
        ),
    ]
